name: Pruuu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bubble: ^1.1.9+1
  intl: ^0.16.1  
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  flutter_secure_storage:
  firebase_core: ^0.4.4+2
  cloud_firestore: ^0.13.4+1
  firebase_messaging: ^6.0.13
  firebase_auth: ^0.16.0
  firebase_storage: 3.0.4
  firebase_remote_config:
  image_cropper: 1.0.2
  image_picker: 0.6.7+10
  path_provider: ^1.6.16
  percent_indicator: "^2.1.7+2"


dev_dependencies:
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bannerAuthLight.png
    - assets/images/bannerAuthDark.png
    - assets/images/perfil-leo.png
    - assets/images/empty_state.png
    - assets/images/error_state.png
